name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m venv .venv
      - run: . .venv/bin/activate && pip install -r requirements.txt && python -c "import fastapi, aiohttp, bs4, jinja2"

  docker-push:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner | lower }}/site-inspector:latest

  deploy-ssh:
    if: github.ref == 'refs/heads/main'
    needs: docker-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v0.1.0  # You can change to v0.1.0 for more stability
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            set -e
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository_owner | lower }}/site-inspector:latest
            docker stop site-inspector || true
            docker rm site-inspector || true
            docker run -d --name site-inspector --restart unless-stopped \
              --env-file /opt/site-inspector/.env -p 8000:8000 \
              ghcr.io/${{ github.repository_owner | lower }}/site-inspector:latest

